"""Central registry for all site adapters, including approved generated drafts."""
import importlib.util
from pathlib import Path
from typing import Any

from job_agent.sites.approval_registry import ApprovalRegistry
from job_agent.sites.base import AdapterRegistry, SiteAdapter
from job_agent.sites.governmentjobs import GovernmentJobsAdapter
from job_agent.sites.greenhouse import GreenhouseAdapter
from job_agent.sites.icims import iCIMSAdapter
from job_agent.sites.workday import WorkdayAdapter


def _load_adapter_class(path: Path) -> Any:
    """Dynamically import a SiteAdapter class from an approved draft file."""
    if not path.exists():
        return None

    spec = importlib.util.spec_from_file_location(path.stem, path)
    if spec is None or spec.loader is None:
        return None

    module = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(module)
    except Exception as exc:
        from loguru import logger

        logger.warning(f"Could not load generated adapter {path}: {exc}")
        return None

    for attr in dir(module):
        obj = getattr(module, attr)
        if isinstance(obj, type) and issubclass(obj, SiteAdapter) and obj is not SiteAdapter:
            return obj
    return None


def build_default_registry() -> AdapterRegistry:
    """Return a registry with all built-in and approved generated adapters."""
    registry = AdapterRegistry()
    registry.register(GreenhouseAdapter)
    registry.register(WorkdayAdapter)
    registry.register(iCIMSAdapter)
    registry.register(GovernmentJobsAdapter)

    # Load approved adapters generated by the Chrome-extension / Adapter Generator loop.
    approval_registry = ApprovalRegistry()
    for platform in approval_registry.approved_platforms():
        adapter_path = approval_registry.generated_dir / f"{platform}_adapter.py"
        adapter_cls = _load_adapter_class(adapter_path)
        if adapter_cls is not None:
            registry.register(adapter_cls)

    return registry
